apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-demo
  name: nginx-demo-svc
  namespace: devops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-demo
  type: NodePort
