# Github Workflow的名称
name: Docker Image CI

# 触发此Workflow的条件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 触发条件满足之后，执行此工作流里的工作任务
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: '进入代码仓库'
      uses: actions/checkout@v3

    - name: '安装docker'
      # You may pin to the exact commit or the version.
      # uses: docker-practice/actions-setup-docker@5d9a5f65f510c01ec5f0bd81d5c95768b1ec032a
      uses: docker-practice/actions-setup-docker@1.0.11

    # 登录到阿里云容器镜像服务
    # registry.cn-hangzhou.aliyuncs.com
    - name: '登录到阿里云的容器镜像服务'
      uses: docker/login-action@v1
      # 配置登录信息，secrets 变量在当前仓库的 Settings -> Secrets 中设置
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_ALI_REGISTRY_USN }}
        password: ${{ secrets.DOCKER_ALI_REGISTRY_PWD }}
    # - name: Build the Docker image
    #   run: docker build . --file build/Dockerfile --tag my-image-name:$(date +%s)

    # 构建镜像并上传到 ghcr.io 容器镜像仓库
    - name: '构建镜像并上传到 aliyun 容器镜像仓库'
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        file: build/Dockerfile
        push: True
        tags: registry.cn-hangzhou.aliyuncs.com/asialeaf/kube-gitops:latest